{
 "title": "Netdata Monitor",
 "time": { "from": "2025-10-10T14:26:26.010Z", "to": "2025-10-14T14:26:26.010Z" },
 "panels": [
  {
   "title": "Disk Used % by Host",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netdata_2h\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"netdata_disk\" and\r\n    (r._field == \"used_gib\" or r._field == \"free_gib\")\r\n  )\r\n  |> group(columns: [\"host\", \"_field\", \"mount\"])\r\n  |> last()\r\n  |> group(columns: [\"host\", \"_field\"])\r\n  |> sum(column: \"_value\")\r\n  |> pivot(rowKey: [\"host\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      host: r.host,\r\n      _value: (r.used_gib / (r.used_gib + r.free_gib)) * 100.0\r\n  }))\r\n  |> keep(columns: [\"_time\", \"host\", \"_value\"])\r\n  |> group(columns: [\"host\"])\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"netdata_2h\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"netdata_disk\" and\r\n    (r._field == \"used_gib\" or r._field == \"free_gib\")\r\n  )\r\n  |> group(columns: [\"host\", \"_field\", \"mount\"])\r\n  |> last()\r\n  |> group(columns: [\"host\", \"_field\"])\r\n  |> sum(column: \"_value\")\r\n  |> pivot(rowKey: [\"host\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      host: r.host,\r\n      used_gib:  math.round(x: r.used_gib * 100.0) / 100.0,\r\n      free_gib:  math.round(x: r.free_gib * 100.0) / 100.0,\r\n      total_gib: math.round(x: (r.used_gib + r.free_gib) * 100.0) / 100.0,\r\n      used_percent: (r.used_gib / (r.used_gib + r.free_gib)) * 100.0\r\n  }))\r\n  |> keep(columns: [\"_time\",\"host\",\"used_percent\",\"used_gib\",\"free_gib\",\"total_gib\"])\r\n  |> sort(columns: [\"host\"])\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"netdata_2h\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"netdata_temp\" and r._field == \"celsius\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n// keep 'host' grouped: one line per RPi\r\n"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"netdata_2h\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"netdata_mem\" and r._field == \"used_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n// keep 'host' in the group key so each host becomes its own series\r\n"
    }
   ]
  },
  {
   "title": "RPI Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"netdata_2h\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"netdata_load\" and r._field == \"load1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"netdata_2h\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"netdata_cpu\" and r._field == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  // keep 'host' in the group key so each host becomes its own series\r\n"
    }
   ]
  }
 ]
}